module Exception2MessageMapper
def extend_object(cl);end
def def_e2message(k, c, m);end
def def_exception(k, n, m, s = nil);end
def Raise(*args);end
def Fail(*args);end
def e2mm_message(klass, exp);end
def message(klass, exp);end
def self.extend_object(cl);end
def self.def_e2message(k, c, m);end
def self.def_exception(k, n, m, s = nil);end
def self.Raise(*args);end
def self.Fail(*args);end
def self.e2mm_message(klass, exp);end
def self.message(klass, exp);end
def bind(cl);end
def Raise(*args);end
def Fail(*args);end
def fail(*args);end
def def_e2message(c, m);end
def def_exception(n, m, s = nil);end
end
class Exception2MessageMapper::ErrNotRegisteredException < StandardError
include Kernel
def self.exception(*args);end
end
class ThreadsWait < Object
include Kernel
def self.included(mod);end
def self.all_waits(*args);end
def self.bind(cl);end
def self.Raise(*args);end
def self.Fail(*args);end
def self.def_e2message(c, m);end
def self.def_exception(n, m, s = nil);end
def self.included(mod);end
def self.all_waits(*args);end
def Raise(*args);end
def Fail(*args);end
def threads();end
def empty?();end
def finished?();end
def join(*args);end
def join_nowait(*args);end
def next_wait(*args);end
def all_waits();end
end
class ThreadsWait::ErrNoWaitingThread < StandardError
include Kernel
def self.exception(*args);end
end
class ThreadsWait::ErrNoFinishedThread < StandardError
include Kernel
def self.exception(*args);end
end
class ThreadsWait < Object
include Kernel
def self.included(mod);end
def self.all_waits(*args);end
def self.bind(cl);end
def self.Raise(*args);end
def self.Fail(*args);end
def self.def_e2message(c, m);end
def self.def_exception(n, m, s = nil);end
def self.included(mod);end
def self.all_waits(*args);end
def Raise(*args);end
def Fail(*args);end
def threads();end
def empty?();end
def finished?();end
def join(*args);end
def join_nowait(*args);end
def next_wait(*args);end
def all_waits();end
end
class ThreadsWait::ErrNoWaitingThread < StandardError
include Kernel
def self.exception(*args);end
end
class ThreadsWait::ErrNoFinishedThread < StandardError
include Kernel
def self.exception(*args);end
end
